[package]
name = "test-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { path = "../ast" }
parse = { path = "../parse" }
ir = { path = "../ir" }
typing = { path = "../typing" }
eval = { path = "../eval" }

[lib]
proc-macro = true